import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import * as inventoryApi from "@/services/api/inventory";

type Row = Record<string, any>;
const statusColors: Record<string, string> = { Pending: "text-[#c0392b]", "In Transit": "text-[#b07b12]", Delivered: "text-[#2e8b57]" };

export default function DispatchDashboard() {
  const [date, setDate] = useState(""); const [refreshKey, setRefreshKey] = useState(0); const [search, setSearch] = useState(""); const [truck, setTruck] = useState("All trucks"); const [status, setStatus] = useState("All statuses"); const [sort, setSort] = useState("so_number"); const [descending, setDescending] = useState(false);
  const query = useQuery({ queryKey: ["dispatch-dashboard", date, refreshKey], queryFn: () => inventoryApi.getDispatchDashboard(date || undefined, refreshKey > 0), refetchInterval: 60_000, refetchIntervalInBackground: false });
  const data = query.data as any; const k = data?.kpis ?? {}; const all = (data?.orders ?? []) as Row[];
  const trucks = Array.from(new Set(all.map(x => x.truck_plate).filter(Boolean))).sort();
  const rows = useMemo(() => all.filter(x => (!search || `${x.so_number} ${x.customer} ${x.salesperson}`.toLowerCase().includes(search.toLowerCase())) && (truck === "All trucks" || x.truck_plate === truck) && (status === "All statuses" || x.status === status)).sort((a,b) => { const av=String(a[sort] ?? "").toLowerCase(), bv=String(b[sort] ?? "").toLowerCase(); return (av < bv ? -1 : av > bv ? 1 : 0) * (descending ? -1 : 1); }), [all, search, truck, status, sort, descending]);
  const setSortBy = (key: string) => { if (sort === key) setDescending(v => !v); else { setSort(key); setDescending(false); } };
  const pct = (key: string) => `${Number(k[`${key}_pct`] ?? 0).toFixed(1)}%`;
  const table = (title: string, items: Row[] = []) => <section className="mt-5 border border-[#e4e3df] bg-white p-5"><div className="micro text-[#77787b]">{title}</div><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-[#e4e3df]">{["name","sos","pending","in_transit","delivered"].map(c => <th className="cursor-pointer py-2" key={c} onClick={() => setSortBy(c)}>{c.replace("_", " ").toUpperCase()}</th>)}</tr></thead><tbody>{items.map(x => <tr className="border-b border-[#efeeeb]" key={x.name}><td className="py-2">{x.name}</td><td>{x.sos}</td><td>{x.pending}</td><td>{x.in_transit}</td><td>{x.delivered}</td></tr>)}</tbody></table></div></section>;
  return <div>
    <header className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><div className="micro text-[#77787b]">RARE GLOBAL FOOD TRADING CORP.</div><h2 className="display-face mt-2 text-3xl font-bold">Dispatch Manifest</h2><p className="mt-1 text-sm text-[#55565a]">Live dispatch tracking — {data?.date ?? "—"}</p></div><div className="flex items-center gap-2 text-xs"><span className="rounded-full border border-[#7aa987] px-3 py-1 text-[#1e7b44]">Synced {data?.synced_at ?? "—"} PHT</span><button className="button-black rounded px-4 py-2" onClick={() => query.refetch()}>Refresh</button></div></header>
    <div className="mb-4 flex flex-wrap items-center gap-3 text-xs"><label className="flex items-center gap-2">Date <input type="date" value={date} onChange={e=>setDate(e.target.value)} className="border px-2 py-2" /></label><span className="text-[#77787b]">Source: {data?.source ?? "Confirmed SO — IntelliFleet"} · Cross-checked: {data?.cross_checked ?? "Zoho Inventory"}</span></div>
    {data?.sync_error && <div className="mb-4 border border-[#c0392b] bg-[#fff5f4] p-3 text-sm text-[#c0392b]">Sync error: {data.sync_error}</div>}
    {!!data?.exceptions?.length && <div className="mb-5 border border-[#c0392b] bg-[#fff5f4] p-4 text-sm text-[#c0392b]"><b>{data.exceptions.length} orders need attention this sync</b>{data.exceptions.map((x: Row) => <div key={`${x.so_number}-${x.reason}`}>{x.so_number} — {x.reason}</div>)}</div>}
    <div className="grid gap-3 md:grid-cols-5">{[["SALES ORDERS TODAY","sales_orders_today","total"],["TRUCKS DEPLOYED","trucks_deployed","routes running today"],["PENDING","pending","awaiting dispatch"],["IN TRANSIT","in_transit","shipped or departed"],["DELIVERED","delivered","fulfilled in Zoho"]].map(([label,key,sub]) => <div className="border border-[#e4e3df] bg-white p-4" key={key}><div className="display-face text-3xl font-bold">{k[key] ?? 0}</div><div className="mt-2 text-xs uppercase tracking-[.12em] text-[#77787b]">{label}</div><div className="mt-2 text-xs text-[#77787b]">{key === "pending" || key === "in_transit" || key === "delivered" ? pct(key) : sub}</div></div>)}</div>
    <section className="mt-5 border border-[#e4e3df] bg-white p-5"><div className="flex justify-between"><div className="micro text-[#77787b]">Dispatch progress</div><span className="text-sm">{k.sales_orders_today ?? 0} orders</span></div><div className="mt-4 flex h-3 overflow-hidden bg-[#efeeeb]"><div className="bg-[#c0392b]" style={{width:pct("pending")}}/><div className="bg-[#d79a25]" style={{width:pct("in_transit")}}/><div className="bg-[#2e8b57]" style={{width:pct("delivered")}}/></div><div className="mt-3 flex gap-4 text-xs"><span>Pending {k.pending ?? 0}</span><span>In Transit {k.in_transit ?? 0}</span><span>Delivered {k.delivered ?? 0}</span></div></section>
    {table("Summary per Truck", data?.trucks)}{table("Summary per Salesperson", data?.salespeople)}
    <section className="mt-5 border border-[#e4e3df] bg-white p-5"><div className="micro text-[#77787b]">Pending list</div>{(data?.pending_orders ?? []).map((x: Row) => <div className="border-b border-[#efeeeb] py-2 text-sm" key={x.so_number}>{x.so_number} · {x.customer} · {x.truck}</div>)}</section>
    <section className="mt-5 border border-[#e4e3df] bg-white p-5"><div className="flex flex-wrap items-center gap-2"><div className="micro mr-auto text-[#77787b]">Sales Orders · {rows.length} of {all.length} shown · {rows.length} line orders</div><input className="border px-2 py-2 text-sm" placeholder="Search SO, customer, sales agent" value={search} onChange={e=>setSearch(e.target.value)}/><select className="border px-2 py-2 text-sm" value={truck} onChange={e=>setTruck(e.target.value)}><option>All trucks</option>{trucks.map(x=><option key={x}>{x}</option>)}</select><select className="border px-2 py-2 text-sm" value={status} onChange={e=>setStatus(e.target.value)}><option>All statuses</option><option>Pending</option><option>In Transit</option><option>Delivered</option></select></div><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-[#e4e3df]">{[["so_number","SO #"],["customer","CUSTOMER"],["truck_plate","TRUCK"],["salesperson","SALES AGENT"],["status","STATUS"]].map(([key,label])=><th className="cursor-pointer py-2" key={key} onClick={()=>setSortBy(key)}>{label}</th>)}</tr></thead><tbody>{rows.map(x=><tr className="border-b border-[#efeeeb]" key={x.salesorder_id}><td className="py-2 font-semibold">{x.so_number}</td><td>{x.customer}<div className="text-[#77787b]">{x.city}</div></td><td>{x.truck_plate}<div className="text-[#77787b]">{x.driver_helper}</div></td><td>{x.salesperson}</td><td className={statusColors[x.status] ?? ""}>{x.status}</td></tr>)}</tbody></table></div></section>
  </div>;
}
