import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import * as inventoryApi from "@/services/api/inventory";

type Row = Record<string, any>;
const statusColors: Record<string, string> = { Pending: "text-[#c0392b]", "In Transit": "text-[#b07b12]", Delivered: "text-[#2e8b57]" };

export default function DispatchDashboard() {
  const [date, setDate] = useState(""); const [refreshKey, setRefreshKey] = useState(0); const [search, setSearch] = useState(""); const [truck, setTruck] = useState("All trucks"); const [status, setStatus] = useState("All statuses"); const [sort, setSort] = useState("so_number"); const [descending, setDescending] = useState(false); const [pendingOpen, setPendingOpen] = useState(false); const [cardLimit, setCardLimit] = useState(10);
  const query = useQuery({ queryKey: ["dispatch-dashboard", date, refreshKey], queryFn: () => inventoryApi.getDispatchDashboard(date || undefined, refreshKey > 0), refetchInterval: 60_000, refetchIntervalInBackground: false });
  const data = query.data as any; const k = data?.kpis ?? {}; const all = (data?.orders ?? []) as Row[];
  const trucks = Array.from(new Set(all.map(x => x.truck_plate).filter(Boolean))).sort();
  const rows = useMemo(() => all.filter(x => (!search || `${x.so_number} ${x.customer} ${x.salesperson}`.toLowerCase().includes(search.toLowerCase())) && (truck === "All trucks" || x.truck_plate === truck) && (status === "All statuses" || x.status === status)).sort((a,b) => { const av=String(a[sort] ?? "").toLowerCase(), bv=String(b[sort] ?? "").toLowerCase(); return (av < bv ? -1 : av > bv ? 1 : 0) * (descending ? -1 : 1); }), [all, search, truck, status, sort, descending]);
  const setSortBy = (key: string) => { if (sort === key) setDescending(v => !v); else { setSort(key); setDescending(false); } };
  const pct = (key: string) => `${Number(k[`${key}_pct`] ?? 0).toFixed(1)}%`;
  const table = (title: string, items: Row[] = []) => <section className="mt-4 border border-[#e4e3df] bg-white p-3 sm:mt-5 sm:p-5"><div className="micro text-[#77787b]">{title}</div><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr className="border-b border-[#e4e3df]">{["name","sos","pending","in_transit","delivered"].map(c => <th className="cursor-pointer whitespace-nowrap py-2 pr-3" key={c} onClick={() => setSortBy(c)}>{c.replace("_", " ").toUpperCase()}</th>)}</tr></thead><tbody>{items.map(x => <tr className="border-b border-[#efeeeb]" key={x.name}><td className="py-2">{x.name}</td><td>{x.sos}</td><td>{x.pending}</td><td>{x.in_transit}</td><td>{x.delivered}</td></tr>)}</tbody></table></div></section>;
  return <div>
    <header className="mb-4 flex flex-col gap-3 sm:mb-5 sm:flex-row sm:flex-wrap sm:items-end sm:justify-between sm:gap-4"><div><div className="micro text-[#77787b]">RARE GLOBAL FOOD TRADING CORP.</div><h2 className="display-face mt-2 text-2xl font-bold sm:text-3xl">Dispatch Manifest</h2><p className="mt-1 text-sm text-[#55565a]">Live dispatch tracking — {data?.date ?? "—"}</p></div><div className="flex items-center justify-between gap-2 text-xs sm:justify-end"><span className="rounded-full border border-[#7aa987] px-3 py-1 text-[#1e7b44]">Synced {data?.synced_at ?? "—"} PHT</span><button className="button-black inline-flex items-center gap-2 rounded px-4 py-2 disabled:cursor-not-allowed disabled:opacity-70" onClick={() => query.refetch()} disabled={query.isFetching}>{query.isFetching && <span className="inline-block h-3 w-3 animate-spin rounded-full border-2 border-white border-t-transparent" aria-hidden="true" />}{query.isFetching ? "Refreshing…" : "Refresh"}</button></div></header>
    <div className="mb-4 flex flex-col items-start gap-2 text-xs sm:flex-row sm:flex-wrap sm:items-center sm:gap-3"><label className="flex items-center gap-2">Date <input type="date" value={date} onChange={e=>setDate(e.target.value)} className="border px-2 py-2" /></label><span className="break-words text-[#77787b]">Source: {data?.source ?? "Confirmed SO — IntelliFleet"} · Cross-checked: {data?.cross_checked ?? "Zoho Inventory"}</span></div>
    {data?.sync_error && <div className="mb-4 border border-[#c0392b] bg-[#fff5f4] p-3 text-sm text-[#c0392b]">Sync error: {data.sync_error}</div>}
    {!!data?.exceptions?.length && <div className="mb-5 border border-[#c0392b] bg-[#fff5f4] p-4 text-sm text-[#c0392b]"><b>{data.exceptions.length} orders need attention this sync</b>{data.exceptions.map((x: Row) => <div key={`${x.so_number}-${x.reason}`}>{x.so_number} — {x.reason}</div>)}</div>}
    <div className="grid grid-cols-2 gap-2 sm:gap-3 md:grid-cols-5">{[["SALES ORDERS TODAY","sales_orders_today","total"],["TRUCKS DEPLOYED","trucks_deployed","routes running today"],["PENDING","pending","awaiting dispatch"],["IN TRANSIT","in_transit","shipped or departed"],["DELIVERED","delivered","fulfilled in Zoho"]].map(([label,key,sub]) => <div className={`border border-[#e4e3df] bg-white p-3 sm:p-4 ${key === "delivered" ? "col-span-2 md:col-span-1" : ""}`} key={key}><div className="display-face text-2xl font-bold sm:text-3xl">{k[key] ?? 0}</div><div className="mt-1.5 text-[11px] uppercase tracking-[.1em] text-[#77787b] sm:mt-2 sm:text-xs sm:tracking-[.12em]">{label}</div><div className="mt-2 text-xs text-[#77787b]">{key === "pending" || key === "in_transit" || key === "delivered" ? pct(key) : sub}</div></div>)}</div>
    <section className="mt-4 border border-[#e4e3df] bg-white p-3 sm:mt-5 sm:p-5"><div className="flex justify-between"><div className="micro text-[#77787b]">Dispatch progress</div><span className="text-sm">{k.sales_orders_today ?? 0} orders</span></div><div className="mt-4 flex h-3 overflow-hidden bg-[#efeeeb]"><div className="bg-[#c0392b]" style={{width:pct("pending")}}/><div className="bg-[#d79a25]" style={{width:pct("in_transit")}}/><div className="bg-[#2e8b57]" style={{width:pct("delivered")}}/></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs"><span>Pending {k.pending ?? 0}</span><span>In Transit {k.in_transit ?? 0}</span><span>Delivered {k.delivered ?? 0}</span></div></section>
    {table("Summary per Truck", data?.trucks)}{table("Summary per Salesperson", data?.salespeople)}
    <section className="mt-4 border border-[#e4e3df] bg-white p-3 sm:mt-5 sm:p-5"><div className="micro text-[#77787b]">Pending list · {data?.pending_orders?.length ?? 0}</div>{(data?.pending_orders ?? []).map((x: Row, i: number) => <div className={`border-b border-[#efeeeb] py-2 text-sm ${i >= 5 && !pendingOpen ? "hidden md:block" : ""}`} key={x.so_number}><div className="flex items-baseline justify-between gap-2"><b>{x.so_number}</b><span className="shrink-0 text-xs text-[#77787b]">{x.truck}</span></div><div className="break-words text-xs text-[#55565a]">{x.customer}</div></div>)}{(data?.pending_orders?.length ?? 0) > 5 && <button className="mt-2 text-xs font-semibold underline md:hidden" onClick={() => setPendingOpen(v => !v)}>{pendingOpen ? "Show less" : `Show all ${data.pending_orders.length}`}</button>}</section>
    <section className="mt-4 border border-[#e4e3df] bg-white p-3 sm:mt-5 sm:p-5"><div className="flex flex-col gap-2 sm:flex-row sm:flex-wrap sm:items-center"><div className="micro mr-auto text-[#77787b]">Sales Orders · {rows.length} of {all.length} shown · {rows.length} line orders</div><input className="w-full border px-2 py-2 text-sm sm:w-auto" placeholder="Search SO, customer, sales agent" value={search} onChange={e=>setSearch(e.target.value)}/><div className="grid grid-cols-2 gap-2 sm:contents"><select className="w-full border px-2 py-2 text-sm sm:w-auto" value={truck} onChange={e=>setTruck(e.target.value)}><option>All trucks</option>{trucks.map(x=><option key={x}>{x}</option>)}</select><select className="w-full border px-2 py-2 text-sm sm:w-auto" value={status} onChange={e=>setStatus(e.target.value)}><option>All statuses</option><option>Pending</option><option>In Transit</option><option>Delivered</option></select></div></div><div className="mt-3 space-y-2 md:hidden">{rows.slice(0, cardLimit).map(x=><div className="border border-[#efeeeb] p-3 text-xs" key={x.salesorder_id}><div className="flex items-start justify-between gap-2"><span className="text-sm font-semibold">{x.so_number}</span><span className={`font-semibold ${statusColors[x.status] ?? ""}`}>{x.status}</span></div><div className="mt-1 break-words text-sm">{x.customer}</div><div className="text-[#77787b]">{x.city}</div><div className="mt-2 flex items-start justify-between gap-3 text-[#55565a]"><span className="break-words">{x.truck_plate}{x.driver_helper ? <span className="block text-[#77787b]">{x.driver_helper}</span> : null}</span><span className="break-words text-right">{x.salesperson}</span></div></div>)}{rows.length > cardLimit && <button className="w-full border border-[#d8d7d2] py-2 text-xs font-semibold" onClick={() => setCardLimit(n => n + 10)}>Show more ({rows.length - cardLimit} left)</button>}</div><div className="mt-3 hidden overflow-x-auto md:block"><table className="w-full text-left text-xs"><thead><tr className="border-b border-[#e4e3df]">{[["so_number","SO #"],["customer","CUSTOMER"],["truck_plate","TRUCK"],["salesperson","SALES AGENT"],["status","STATUS"]].map(([key,label])=><th className="cursor-pointer whitespace-nowrap py-2 pr-3" key={key} onClick={()=>setSortBy(key)}>{label}</th>)}</tr></thead><tbody>{rows.map(x=><tr className="border-b border-[#efeeeb]" key={x.salesorder_id}><td className="py-2 font-semibold">{x.so_number}</td><td>{x.customer}<div className="text-[#77787b]">{x.city}</div></td><td>{x.truck_plate}<div className="text-[#77787b]">{x.driver_helper}</div></td><td>{x.salesperson}</td><td className={statusColors[x.status] ?? ""}>{x.status}</td></tr>)}</tbody></table></div></section>
  </div>;
}


